<a href="https://colab.research.google.com/github/SachinMhetre678/Machine_Learning/blob/main/NumPy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
myarr = np.array(mylist)

In [5]:
myarr

array([1, 2, 3])

myarr

In [8]:
type(myarr)

numpy.ndarray

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
my_matrix

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [24]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [25]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
np.random.rand(5,2)

array([[0.63254757, 0.77558524],
       [0.3166248 , 0.49864156],
       [0.02280101, 0.26380627],
       [0.54764741, 0.19801641],
       [0.32659155, 0.61840289]])

In [33]:
np.random.randn(10)

array([-1.26733768,  0.75572668, -0.18306168,  2.11616136, -0.73055347,
        0.27549435,  0.30217468,  0.40267517,  0.26837473,  0.75351482])

In [34]:
np.random.randn(2,3)

array([[-0.19609115, -0.27572209,  1.22891504],
       [ 0.10517329,  0.99834346,  0.7369717 ]])

In [36]:
np.random.randint(0,101,(4,5))

array([[79, 12, 51, 12, 41],
       [ 8, 84, 51, 15, 64],
       [48, 97,  2, 57, 26],
       [13, 52, 39, 58, 86]])

In [37]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [38]:
arr = np.arange(0,25)

In [40]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
ranarr = np.random.randint(0,101,10)

In [43]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [46]:
ranarr.min()

2

In [47]:
ranarr.argmax()

5

In [48]:
ranarr.argmin()

7

In [49]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [50]:
arr.shape

(25,)

In [51]:
arr = arr.reshape(5,5)

In [52]:
arr


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
arr.shape

(5, 5)

In [55]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])